# Generated by Django 6.0 on 2025-12-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('assinatura_digital', models.BooleanField(default=False)),
                ('imagem_assinatura', models.ImageField(blank=True, null=True, upload_to='assinaturas/')),
            ],
        ),
    ]
