# Generated by Django 6.0 on 2025-12-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='assinatura_digital',
            new_name='assinatura_valida',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='hash_integridade',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
